INSERT INTO PERSON_CONTACT_TYPE (ID) VALUES ('EMAIL');
INSERT INTO PERSON_CONTACT_TYPE (ID) VALUES ('PHONE');

INSERT INTO PERSON_CONTACT_STATE (ID) VALUES ('WAITED');
INSERT INTO PERSON_CONTACT_STATE (ID) VALUES ('CONFIRMED');
INSERT INTO PERSON_CONTACT_STATE (ID) VALUES ('REMOVED');
