CREATE TABLE CONFIRMATION_STATE(
    ID VARCHAR(20) NOT NULL
    , DESCRIPTION VARCHAR(512)
    , PRIMARY KEY (ID)
);

CREATE TABLE CONFIRMATION(
    ID INT NOT NULL AUTO_INCREMENT
    , CONFIRM_CODE VARCHAR(20) NOT NULL    
    , PERSON_ID INT NOT NULL
    , CONTACT_ID INT NOT NULL        
    , STATE_ID VARCHAR(20) NOT NULL
    , ENTITY_ID INT NOT NULL     
    , LAST_SENDING_DATE TIMESTAMP    
    , PRIMARY KEY (ID)
    , CONSTRAINT FK_CONFIRMATION_1 UNIQUE (CONFIRM_CODE) 
    , CONSTRAINT FK_CONFIRMATION_2 FOREIGN KEY (STATE_ID) REFERENCES CONFIRMATION_STATE(ID)
    , CONSTRAINT FK_CONFIRMATION_3 FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID)
    , CONSTRAINT FK_CONFIRMATION_4 FOREIGN KEY (CONTACT_ID) REFERENCES PERSON_CONTACT(ID)    
);
