INSERT INTO CONFIRMATION_STATE (ID) VALUES ('CREATED');
INSERT INTO CONFIRMATION_STATE (ID) VALUES ('SENT');
INSERT INTO CONFIRMATION_STATE (ID) VALUES ('RESENT');
INSERT INTO CONFIRMATION_STATE (ID) VALUES ('CONFIRMED');
